# Generated by Django 5.2.1 on 2025-05-27 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_department'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantable',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='accounts.department'),
            preserve_default=False,
        ),
    ]
