# Generated by Django 5.2.1 on 2025-05-27 23:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending_1', 'منتظر تایید سرپرست'), ('approved_1', 'تایید توسط سرپرست'), ('rejected_1', 'رد توسط سرپرست'), ('pending_2', 'منتظر تایید مدیر بخش'), ('approved_2', 'تایید توسط مدیر بخش'), ('rejected_2', 'رد توسط مدیر بخش'), ('approved_3', 'تایید نهایی'), ('rejected_3', 'رد نهایی')], default='pending_1', max_length=20),
        ),
    ]
