# Generated by Django 5.2.1 on 2025-05-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_leaverequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='start_day',
            field=models.DurationField(),
        ),
    ]
