# Generated by Django 5.2.1 on 2025-05-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_leaverequest_start_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='start_day',
            field=models.DateField(),
        ),
    ]
