# Generated by Django 5.2.1 on 2025-05-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_leaverequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending_1', 'منتظر تایید سرپرست'), ('approved_1', 'تایید توسط سرپرست'), ('rejected_1', 'رد توسط سرپرست'), ('pending_2', 'منتظر تایید مدیر بخش'), ('approved_2', 'تایید توسط مدیر بخش'), ('rejected_2', 'رد توسط مدیر بخش'), ('pending_3', 'منتظر تایید مدیر منابع انسانی'), ('approved_3', 'تایید توسط مدیر منابع انسانی'), ('rejected_3', 'رد توسط مدیر منابع انسانی'), ('pending_4', 'منتظر تایید مدیر'), ('approved_4', 'تایید نهایی'), ('rejected_4', 'رد نهایی')], default='pending_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='plantable',
            name='day',
            field=models.CharField(max_length=30, verbose_name='روز'),
        ),
    ]
