# Generated by Django 5.2.1 on 2025-05-31 07:51

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_leaverequest_status_alter_plantable_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='created_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='end_day',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start_day',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
