# Generated by Django 5.2.1 on 2025-05-31 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_leaverequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-created_at']},
        ),
    ]
