# Generated by Django 5.2.1 on 2025-05-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_leaverequest_options_worklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
