# Generated by Django 5.2.1 on 2025-06-01 07:36

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_worklog_end_time_alter_worklog_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='end_time',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='start_time',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
    ]
