# Generated by Django 5.2.1 on 2025-06-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_worklog_date_alter_worklog_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
