# Generated by Django 5.2.1 on 2025-06-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_worklog_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='start_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
