# Generated by Django 5.2.1 on 2025-06-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_worklog_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
