# Generated by Django 5.2.1 on 2025-05-27 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('admin', 'مدیر سیستم'), ('manager', 'مدیریت'), ('site', 'سایت'), ('it', 'آی تی'), ('human_resources', 'منابع انسانی'), ('finance', 'مالی'), ('support', 'پشتیبانی'), ('sales', 'فروش'), ('adminstrative', 'اداری'), ('formal', 'حضوری'), ('content', 'محتوا')], default=None, max_length=35),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, to='accounts.department'),
        ),
    ]
