# Generated by Django 5.2.1 on 2025-05-27 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(default='id=0', on_delete=django.db.models.deletion.CASCADE, to='accounts.department'),
        ),
    ]
