# Generated by Django 5.2.1 on 2025-05-27 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_department_name_alter_profile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_senior_manager',
        ),
        migrations.AddField(
            model_name='department',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
