# Generated by Django 5.2.1 on 2025-05-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='departman',
        ),
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(blank=True, choices=[('unknown', 'تعریف نشده'), ('admin', 'مدیر سیستم'), ('manager', 'مدیریت'), ('site', 'سایت'), ('it', 'آی تی'), ('human_resources', 'منابع انسانی'), ('finance', 'مالی'), ('support', 'پشتیبانی'), ('sales', 'فروش'), ('adminstrative', 'اداری'), ('formal', 'حضوری'), ('content', 'محتوا')], max_length=35, null=True),
        ),
    ]
