# Generated by Django 5.2.1 on 2025-05-28 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_user_departman_alter_department_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(blank=True, choices=[('unknown', 'تعریف نشده'), ('admin', 'مدیر سیستم'), ('manager', 'مدیریت'), ('site', 'سایت'), ('it', 'آی تی'), ('human_resources', 'منابع انسانی'), ('finance', 'مالی'), ('support', 'پشتیبانی'), ('sales', 'فروش'), ('adminstrative', 'اداری'), ('formal', 'حضوری'), ('content', 'محتوا')], default='unknown', max_length=35, null=True),
        ),
    ]
